name: pokedex_new_version
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_modular: ^6.3.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  faker: ^2.1.0
  flutter_lints: ^3.0.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
